SELECT * FROM NOTICE_BOARD;

--글번호순
SELECT * FROM NOTICE_BOARD ORDER BY NOTICE_SEQ DESC

--조회수순
SELECT * FROM NOTICE_BOARD ORDER BY VIEW_CNT DESC

--최신등록일순
SELECT * FROM NOTICE_BOARD ORDER BY REG_DT DESC

--오래된순
SELECT * FROM NOTICE_BOARD ORDER BY REG_DT